/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_HORA_C__
#define __RUST_HORA_C__

#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

void hora_new_bf_index (
    int8_t const * name,
    size_t dimension);

void hora_add (
    int8_t const * name,
    double const * features,
    int8_t const * idx,
    size_t dimension);

char * hora_build (
    int8_t const * name,
    int8_t const * mt);

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_char_ptr {

    char * * ptr;

    size_t len;

    size_t cap;

} Vec_char_ptr_t;

Vec_char_ptr_t hora_search (
    int8_t const * name,
    size_t k,
    double const * features,
    size_t dimension);

void hora_load (
    int8_t const * name,
    int8_t const * _file_path);

void hora_dump (
    int8_t const * name,
    int8_t const * _file_path);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __RUST_HORA_C__ */
